### ISSUE TITLE
Document is misleadingly presenting as an official W3C document

### ISSUE THREAD

**Issue by yatil** [a11yedge/capabilities#12]
The document poses as a W3C document, including the W3C logo, however Community Group documents are not official W3C documents. There is no clear indication that this is the work of a community group and hence not gone through the W3C channels and consensus process people expect from W3C documents.

The only contributors are representatives of UserWay. 

Remove the W3C logo and clearly communicate the document as a UserWay/community group document with the usual disclaimer that community groups are not W3C working groups and are neither specifications nor standards.

**Comment by JaninaSajka** [comment]
This is a frivolous comment, e.g. you clearly haven't even looked through the document itself, or you'd be aware of Appendix B.

**Comment by yatil** [comment]
No, it is not. The [link was attributed to W3C in a document by the DoJ (Mastodon)](https://toot.cafe/@aardrian/112246779124647358) and I noted the missing proper attribution to the community group. 

I looked at the GitHub contributors page and only two people are listed there. I cannot verify that other people have contributed to the document and most people, have no affiliation listed. 

It’s not a frivolous comment, and I insist of not using ad hominem attacks.

Thanks for merging the pull request, that at least shows properly that this is an unofficial document.

**Comment by yatil** [comment]
(FWIW, the issue should be closed as fixed after merging #12, not as “not planned”.)

**Comment by JaninaSajka** [comment]
It is fallacious to presume that all contributions would come via github tracked commits. We have significant numbers of persons with disabilities in W3C/WAI who are unable to function with github. We don't turn their contributions away for such reasons. Furthermore, there has never been a requirement that participants are somehow affiliated with some organization.

**Comment by yatil** [comment]
Sure. Never said otherwise. I just said that it was impossible to verify from my point of view, so I went off the data I had.
